apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: quarkus-rest-native-example
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      application: quarkus-rest-native-example
    name: quarkus-rest-native-example
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/ads--prototype/quarkus-rest-native-example:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: quarkus-rest-native-example
    name: quarkus-rest-native-example
  spec:
    replicas: 1
    selector:
      deploymentConfig: quarkus-rest-native-example
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: quarkus-rest-native-example
          deploymentConfig: quarkus-rest-native-example
        name: quarkus-rest-example
      spec:
        containers:
        - image: ''
          imagePullPolicy: Always
          name: quarkus-rest-example
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 60
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - quarkus-rest-example
        from:
          kind: ImageStreamTag
          name: quarkus-rest-native-example:latest
          namespace: ads--prototype
        lastTriggeredImage: images.paas.redhat.com/ads/quarkus-rest-native@sha256:200bc5744b143ea3302b0df9e131ac19fa33fae930dcc975704c2953fc28a2f6
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      application: quarkus-rest-native-example
    name: quarkus-rest-native-example
  spec:
    ports:
    - name: 8080-http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentConfig: quarkus-rest-native-example
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      application: quarkus-rest-native-example
    name: quarkus-rest-native-example
  spec:
    host: quarkus-rest-native-example.int.us-west.dc.preprod.paas.redhat.com
    port:
      targetPort: 8080-http
    tls:
      termination: edge
    to:
      kind: Service
      name: quarkus-rest-native-example
      weight: 100
    wildcardPolicy: None

